runtime: java
env: flex

automatic_scaling:
  max_num_instances: 1

network:
  session_affinity: true

env_variables:
  SPRING_PROFILES_ACTIVE: 'prod'
  DB_URL: '${DB_URL}'
  DB_USERNAME: '${DB_USERNAME}'
  DB_PASSWORD: '${DB_PASSWORD}'
  TRANSLATE_KEY: '${PROD_TRANSLATE_API_KEY}'
