name: Deploy Project to App Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Tests and Sonarqube Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew test jacocoTestReport sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

  deploy:
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_CREDENTIALS }}
          export_default_credentials: true
      - name: Access Production Secret
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          TRANSLATE_KEY=$(gcloud secrets versions access latest --secret='PROD_TRANSLATE_KEY' --project=${{ secrets.GCP_PROJECT_ID }})
          echo "TRANSLATE_KEY=$TRANSLATE_KEY" >> $GITHUB_ENV
      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          version: v1
          credentials: ${{ secrets.GCP_SERVICE_CREDENTIALS }}
      - name: Test Deployment
        run: |
          echo "Testing deployment..."
          response=$(curl -s -o /dev/null -w "%{http_code}" ${{ steps.deploy.outputs.url }})
          echo "Deployment HTTP status: $response"
          if [[ "$response" -ne 200 ]]; then
            echo "Deployment failed with HTTP status: $response"
            exit 1
          fi
          echo "App is up and running with HTTP status: $response"