name: Deploy Project to App Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Tests and Sonarqube Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew test jacocoTestReport sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          google_api_key: ${{ secrets.LOCAL_TRANSLATE_API_KEY }}  # Used here for whatever purpose necessary in the action

  deploy:
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_CREDENTIALS }}
          export_default_credentials: true
      - name: Access Production Secret
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          echo "TRANSLATE_KEY=$(gcloud secrets versions access latest --secret='projects/${{ secrets.GCP_PROJECT_ID }}/secrets/PROD_TRANSLATE_KEY')" >> $GITHUB_ENV
      - name: Update app.yaml with environment variables
        run: |
          echo "Updating app.yaml with dynamic environment variables..."
          sed -i 's|TRANSLATE_KEY:.*|TRANSLATE_KEY: '"${{ env.TRANSLATE_KEY }}"'|' app.yaml
          sed -i 's|DB_URL:.*|DB_URL: '"${{ secrets.DB_URL }}"'|' app.yaml
          sed -i 's|DB_USERNAME:.*|DB_USERNAME: '"${{ secrets.DB_USERNAME }}"'|' app.yaml
          sed -i 's|DB_PASSWORD:.*|DB_PASSWORD: '"${{ secrets.DB_PASSWORD }}"'|' app.yaml
      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          version: v1
          credentials: ${{ secrets.GCP_SERVICE_CREDENTIALS }}
