name: Deploy Project to App Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test and Sonarqube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up environment for tests
        run: |
          echo "TRANSLATE_KEY=${{ secrets.LOCAL_TRANSLATE_API_KEY }}" >> $GITHUB_ENV
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Test and analyze
        run: ./gradlew test jacocoTestReport sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          TRANSLATE_KEY: ${{ env.TRANSLATE_KEY }}

  deploy:
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set PROD_TRANSLATE_API_KEY for deployment
        run: |
          echo "TRANSLATE_KEY=${{ secrets.PROD_TRANSLATE_API_KEY }}" >> $GITHUB_ENV
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Print environment variables for debugging
        run: |
          echo "TRANSLATE_KEY=${{ env.TRANSLATE_KEY }}"
          echo "DB_URL=${{ env.DB_URL }}"
          echo "DB_USERNAME=${{ env.DB_USERNAME }}"
          echo "DB_PASSWORD=${{ env.DB_PASSWORD }}"

      - name: Build Project
        run: ./gradlew clean build
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          TRANSLATE_KEY: ${{ secrets.PROD_TRANSLATE_API_KEY }}

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: build/libs/soprafs24.jar
          version: v2
          credentials: ${{ secrets.GCP_SERVICE_CREDENTIALS }}
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          TRANSLATE_KEY: ${{ secrets.PROD_TRANSLATE_API_KEY }}

      - name: Test Deployment
        run: curl "${{ steps.deploy.outputs.url }}"
